# Generated by Django 3.2.7 on 2021-10-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignupcredentials',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersignupcredentials',
            name='userName',
        ),
        migrations.AddField(
            model_name='usersignupcredentials',
            name='user_name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersignupcredentials',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('victims_fname', models.CharField(max_length=20)),
                ('victims_lname', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('idproof_number', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.usersignupcredentials')),
            ],
        ),
    ]
