# Generated by Django 3.2.7 on 2021-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211014_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupcredentials',
            name='user_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
