# Generated by Django 3.2.7 on 2021-10-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20211014_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignUpCredential',
            new_name='signup',
        ),
    ]
