# Generated by Django 3.2.7 on 2021-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_usersignupcredential_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='message',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.TextField(max_length=50),
        ),
    ]
