# Generated by Django 3.2.7 on 2021-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20211014_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='idprooof',
            field=models.FileField(default='', null=True, upload_to='data/<django.db.models.fields.AutoField>/id'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='images',
            field=models.ImageField(default='', null=True, upload_to='data/<django.db.models.fields.AutoField>/images'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vedios',
            field=models.FileField(default='', null=True, upload_to='data/<django.db.models.fields.AutoField>/vedios'),
        ),
    ]
