# Generated by Django 3.2.7 on 2021-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20211014_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='idprooof',
            field=models.FileField(default='', null=True, upload_to='data/id'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='images',
            field=models.ImageField(default='', null=True, upload_to='data/images'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vedios',
            field=models.FileField(default='', null=True, upload_to='data/vedios'),
        ),
    ]
