# Generated by Django 3.2.7 on 2021-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20211117_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='idprooof',
            field=models.FileField(null=True, upload_to='data/id/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(null=True, upload_to='data/images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vedio',
            field=models.FileField(null=True, upload_to='data/vedios/'),
        ),
    ]
