# Generated by Django 3.2.7 on 2021-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20211205_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phnumber',
            field=models.IntegerField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
