# Generated by Django 3.2.7 on 2021-12-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_complaint_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.signup'),
        ),
    ]
