# Generated by Django 3.2.7 on 2021-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_complaint_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mssg', models.TextField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
