# Generated by Django 3.2.7 on 2021-12-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20211213_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.FileField(upload_to='data/images/'),
        ),
    ]
