# Generated by Django 3.2.7 on 2021-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
