# Generated by Django 3.2.7 on 2021-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_complaint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.FileField(upload_to='data/imgs/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vedio',
            field=models.FileField(upload_to='data/vids/'),
        ),
    ]
