# Generated by Django 3.2.7 on 2021-12-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20211213_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
