# Generated by Django 3.2.7 on 2021-12-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='policeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('psemail', models.EmailField(max_length=254)),
                ('psnumber', models.IntegerField()),
            ],
        ),
    ]
