# Generated by Django 3.2.7 on 2021-12-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_policedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='NA', max_length=50),
        ),
    ]
